[profiles.user]
user_id = "@ehtrude:matrix.org"

[settings]
request_timeout = 180

[settings.image_preview]
protocol.type = "halfblocks"
protocol.font_size = [ 11, 26 ]
size = { height = 10, width = 66 }

[settings.notifications]
enabled = true

[layout]
style = "restore"

[settings.users]
"@ehtrude:matrix.org" = { name = "Trude", color = "light-red" }
